#!/bin/zsh
cd ${2:-/home/arctair/ws/fall-color-history/scripts}
curl -sf https://maps2.dnr.state.mn.us/cgi-bin/fall_colors_json.cgi | \
  ./cgi2json | \
  jq '{locations:.}' | \
  curl -svXPUT ${1:-yagni:8081}/snapshots/latest \
    -Hcontent-type:application/json \
    -d @-
cd -
